export const games = [
  {
    id: 1,
    title: "Krunker.io",
    image: "https://krunkergame.io/data/image/posts/krunker-io-game-banner1.jpg",
    category: "FPS",
    rating: 4.7,
    isFavorite: true,
    url: "https://krunker.io/",
  },
  {
    id: 2,
    title: "Agar.io",
    image: "/images/agar.png",
    category: "Multiplayer IO",
    rating: 4.5,
    isFavorite: false,
    url: "https://agar.io/",
  },
  {
    id: 3,
    title: "Slither.io",
    image: "/images/slither.png",
    category: "Multiplayer IO",
    rating: 4.3,
    isFavorite: true,
    url: "https://slither.io/",
  },
  {
    id: 4,
    title: "Shell Shockers",
    image: "/images/shellshockers.png",
    category: "FPS",
    rating: 4.2,
    isFavorite: false,
    url: "https://shellshock.io/",
  },
  {
    id: 5,
    title: "Surviv.io",
    image: "/images/surviv.png",
    category: "Battle Royale",
    rating: 4.4,
    isFavorite: false,
    url: "https://surviv.io/",
  },
  {
    id: 6,
    title: "Venge.io",
    image: "/images/venge.png",
    category: "FPS",
    rating: 4.1,
    isFavorite: true,
    url: "https://venge.io/",
  },
]

